### ISSUE TITLE
TypeError: Cannot read property '0.5691747572815534' of undefined

### ISSUE THREAD

**Issue by Simone-cogno** [winkjs/wink-regression-tree#14]
I have some fields with float numbers. And I get this error. Do this library support float numbers? Or what can be the issue?

Here my column config:
```
var columns = [
        {name: 'x', categorical: false, exclude: false}, //number
        {name: 'y', categorical: false, target: true}, //float
        {name: 'z', categorical: false, exclude: false},//number
        {name: 'q', categorical: false, exclude: false}, //float
        {name: 'k', categorical: false, exclude: false} //float
    ];
```
Error stack: 
```
TypeError: Cannot read property '0.5691747572815534' of undefined
    at transformRow (/Users/xxx/WebstormProject/xxx/node_modules/wink-regression-tree/src/wink-regression-tree.js:167:23)
    at Object.ingest (/Users/xxx/WebstormProject/xxx/node_modules/wink-regression-tree/src/wink-regression-tree.js:672:19)

```

Edit: I've also tried to convert float to number but I get the same error: 
```
TypeError: Cannot read property '57' of undefined
    at transformRow (/Users/scogno/WebstormProject/esp_server_relaunch/node_modules/wink-regression-tree/src/wink-regression-tree.js:167:23)
    at Object.ingest (/Users/scogno/WebstormProject/esp_server_relaunch/node_modules/wink-regression-tree/src/wink-regression-tree.js:672:19)
```

Oh, maybe I've understood. I think we cannot use numeric features right? It only works for the target value.

**Comment by sanjayaksaxena** [comment]
Hi @Simone-cogno 

Yes, currently it supports only categorical values as input – one workaround is to quantize and assign a category to a range – could possibly use [`boxplot`](http://winkjs.org/wink-statistics/data.html#.boxplot) to achieve it.

Hope it helps.

Best,
Sanjaya

**Comment by sanjayaksaxena** [comment]
If you could share some insight of the use-case, we will be able to assist you better... Sanjaya

**Comment by Simone-cogno** [comment]
You are right, I can eventually create some range of values and give it a label.

My use case is a bit experimental. I'm trying to find rules to discover what is the cause of the battery discharge of some IOT devices. I already did some correlation analysis but I'm interested of the result of this other type of prediction model.

**Comment by sanjayaksaxena** [comment]
Do you think that a different perspective will help i.e. multi-label classifier – different levels of battery voltages predicted from a set of continuous or categorical values? If yes, then you may consider using [**`perceptron`**](http://winkjs.org/wink-perceptron/index.html)...

There is even a [**`real-time regression`**](http://winkjs.org/wink-statistics/streaming.html#simpleLinearRegression) in wink... Some of them can easily run on a Raspberry Pi as well!

I am closing the issue for now. Do reach us if you need any further help.
